### ISSUE TITLE
玩转一下YAML

### ISSUE THREAD

**Issue by bingoohuang** [bingoohuang/blog#142]
yaml多行文本，怎么玩，[在线示例](https://codebeautify.org/yaml-to-json-xml-csv/cb8cb203)

```yaml
# https://yaml-multiline.info/
# yaml-cheatsheet https://gist.github.com/jonschlinkert/5170877
data10: >
   Folded scalar indicator
   + Keep chomp modifier
   - Strip chomp modifier 
   Single newline at end (clip)

data11: >-
   Folded scalar indicator
   + Keep chomp modifier
   - Strip chomp modifier 
   Single newline at end (clip)

data12: >+
   Folded scalar indicator
   + Keep chomp modifier
   - Strip chomp modifier 
   Single newline at end (clip)

data20: |
   Block scalar indicator.
   + Keep chomp modifier
   - Strip chomp modifier 
   Single newline at end (clip)

data21: |-
   Block scalar indicator.
   + Keep chomp modifier
   - Strip chomp modifier 
   Single newline at end (clip)

data22: |+
   Block scalar indicator.
   + Keep chomp modifier
   - Strip chomp modifier 
   Single newline at end (clip)

```

```json
{
	"data10": "Folded scalar indicator + Keep chomp modifier - Strip chomp modifier  Single newline at end (clip)\n",
	"data11": "Folded scalar indicator + Keep chomp modifier - Strip chomp modifier  Single newline at end (clip)",
	"data12": "Folded scalar indicator + Keep chomp modifier - Strip chomp modifier  Single newline at end (clip)\n\n",
	"data20": "Block scalar indicator.\n+ Keep chomp modifier\n- Strip chomp modifier \nSingle newline at end (clip)\n",
	"data21": "Block scalar indicator.\n+ Keep chomp modifier\n- Strip chomp modifier \nSingle newline at end (clip)",
	"data22": "Block scalar indicator.\n+ Keep chomp modifier\n- Strip chomp modifier \nSingle newline at end (clip)"
}
```

**Comment by bingoohuang** [comment]
[online](https://codebeautify.org/yaml-validator/cb895a79)

```yaml
---
# javaBean复杂属性和SpringBoot的Yaml配置还能这么玩
# https://mp.weixin.qq.com/s/561bmmPUCFOFpPkvcfTPgQ
suc:
  www:
    username: suke
    user-age: 24
    user-sexy: 1
    # array  String[] bestFriends
    #best-friends: [aa,bb,cc]  #这种也是可以的
    best-friends:
      - dd
      - ee
    # list  List<String> hobbies
    hobbies:
      - eat
      - drink
      - 写博客 ：xxxxx
      - 写公众号：苏克分享
    #  list  List<Suke>
    sukes:
      - {username: 3001, user-age: 24, user-sexy: 1}
      - {username: 3002, user-age: 24, user-sexy: 0}
      - username: 3003
        user-age: 24
        user-sexy: 1
    # map  Map<String,String>
    nick-name: {aa: suke01, bb: suke02}
    # map  Map<String,List<Suke>>
    all-friends:
      first:
        - {username: 1001, user-age: 24, user-sexy: 1}
        - username: 1003
          user-age: 24
          user-sexy: 1
      second:
        - {username: 2001, user-age: 24, user-sexy: 1}

    # set  Set<String>
    s: [aa, bb, cc]
#      - aa
#      - bb
#      - cc
```

**Comment by bingoohuang** [comment]
# yaml

摘自[YAML Tutorial: Get Started With YAML in 5 Minutes](https://betterprogramming.pub/yaml-tutorial-get-started-with-yaml-in-5-minutes-549d462972d8)

## 多个文档  Multi-document support

You can have multiple YAML documents in a single YAML file to make file organization or data parsing easier.

The separation between each document is marked by three dashes (---)

```yaml
---
player: playerOne
action: attack (miss)
---
player: playerTwo
action: attack (hit)
```

## Built-in commenting

[在线](https://codebeautify.org/yaml-to-json-xml-csv/cbf8d10c)

YAML allows you to add comments to files using the hash symbol (#) similar to Python comments.

```yaml
key: #Here is a single-line comment 
  - value line 5
  #Here is a 
  #multi-line comment
  - value line 13
```

## 显式类型转换

[在线](https://codebeautify.org/yaml-to-json-xml-csv/cb5c9d49)

```yaml
# The value should be an int:
is-an-int: !!int 14.10
# Turn any value to a string:
is-a-str: !!str 67.43
# The next value should be a boolean:
is-a-bool: !!bool yes
```

## Scalars and mapping

[online](https://codebeautify.org/yaml-to-json-xml-csv/cbddc6d8)

```yaml
integer: 25
hex: 0x12d4 #evaluates to 4820
octal: 023332 #evaluates to 9946
float: 25.0
exponent: 12.3015e+05 #evaluates to 1230150.0
boolean: Yes
string: "25"
infinity: .inf # evaluates to infinity
neginf: -.Inf #evaluates to negative infinity
not: .NAN #Not a Number
```
