### ISSUE TITLE
Postgre

### ISSUE THREAD

**Issue by bingoohuang** [bingoohuang/blog#195]
```yaml
# ./docker-compose.yaml
version: '3.2'

services:
  pg:
    image: postgres:12.4
    ports:
      - 2001:5432
    volumes:
      - ./init-pg.sh:/docker-entrypoint-initdb.d/init-pg.sh
    environment:
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=pg
      - POSTGRES_DB=pg
```

```sh
#!/bin/sh

set -e

psql -v ON_ERROR_STOP=1 --username pg --dbname pg <<-EOSQL
    CREATE DATABASE pg;
    GRANT ALL PRIVILEGES ON DATABASE pg TO pg;
EOSQL
```
